### ISSUE TITLE
using more than one pool on an Iet iSCSI server with ZFS does not work

### ISSUE THREAD

**Issue by koebi001** [proxmox/pve-storage#2]
The contents of the first pool which get used gets cached without the information of the pool name. Using an other pool later on does not invalidate and recreate the cache and therefore uses the wrong information.

**Comment by ThomasLamprecht** [comment]
Hi,

Closing due to old version:

Also, GitHub is only used as mirror, please direct guture issues to one of the places linked in:
https://pve.proxmox.com/pve-docs/pve-admin-guide.html#getting_help

thanks!
