### ISSUE TITLE
timeout too short for Iet

### ISSUE THREAD

**Issue by koebi001** [proxmox/pve-storage#4]
For example creating a ZFS volume on an Iet server often fails with a tiemout. The default timeout of 5sec is too short for creating a volume via ssh especially if the server is under load.
Please consider to rise the timeout to a much longer time. I think this should be done for all commands because all the zfs and zpool commands will take a longer time if a lot of volumes/snapshots exist on the server which is not uncommon.

**Comment by ThomasLamprecht** [comment]
Hi,

Closing due to old version:

Also, GitHub is only used as mirror, please direct guture issues to one of the places linked in:
https://pve.proxmox.com/pve-docs/pve-admin-guide.html#getting_help

thanks!
