### ISSUE TITLE
`glusterfs_is_mounted` in `PVE::Storage::GlusterfsPlugin` wrongly returning that a volume is unmounted

### ISSUE THREAD

**Issue by zoldar** [proxmox/pve-storage#6]
There is a problem that prevents that system from carrying most of the standard tasks on Gluster volumes. I've tracked down the case to the changeset https://github.com/proxmox/pve-storage/commit/80b647882e629f6fda9328008eeb5d3365f0c9a0. The problem is that in the output of `PVE::ProcFSTools::parse_proc_mounts()`, the part of every mount entry is full source description as in `172.16.11.110:system_mail1`, while the `$volume` holds only the second part (`system_mail1` in that example). Additional processing should be done when matching the mountpoints.

I'm not 100% sure, but I suspect that the same holds for the NFS plugin.

**Comment by ThomasLamprecht** [comment]
Hi,

Closing due to old version:

Also, GitHub is only used as mirror, please direct guture issues to one of the places linked in:
https://pve.proxmox.com/pve-docs/pve-admin-guide.html#getting_help

thanks!
