### ISSUE TITLE
Last PVE-Storage Update breaks glusterfs support

### ISSUE THREAD

**Issue by justnx** [proxmox/pve-storage#7]
After applying latest storage lib update: libpve-storage-perl:amd64 4.0-45 i'm getting:
file /etc/pve/storage.cfg line 14 (skip section 'gfs-vol0'): storage does not support content type 'rootdir'

And all my glusterfs mapped VM's broke up. I can't select any glusterfs volume anymore via storage tab.

Reverting: libpve-storage-perl:amd64 back to Version: 4.0-42 seems to fix it again.

**Comment by ThomasLamprecht** [comment]
Hi,

Closing due to old version:

Also, GitHub is only used as mirror, please direct guture issues to one of the places linked in:
https://pve.proxmox.com/pve-docs/pve-admin-guide.html#getting_help

thanks!
