### ISSUE TITLE
vzdump breaks backup of containers with storage pass through

### ISSUE THREAD

**Issue by TuncTaylan** [proxmox/pve-storage#8]
With the latest update, the backup of containers with storage pass through fails with following error:
unable to parse volume ID

Here is the relevant log of my latest backup:
`101: 2020-11-23 00:02:12 INFO: Starting Backup of VM 101 (lxc)
101: 2020-11-23 00:02:12 INFO: status = running
101: 2020-11-23 00:02:12 INFO: CT Name: TimeCapsule
101: 2020-11-23 00:02:12 INFO: including mount point rootfs ('/') in backup
101: 2020-11-23 00:02:12 INFO: excluding bind mount point mp0 ('/mnt/XXX-MBP') from backup (not a volume)
101: 2020-11-23 00:02:12 INFO: excluding bind mount point mp1 ('/mnt/XXX-MBP') from backup (not a volume)
101: 2020-11-23 00:02:12 INFO: backup mode: snapshot
101: 2020-11-23 00:02:12 INFO: ionice priority: 7
101: 2020-11-23 00:02:12 INFO: create storage snapshot 'vzdump'
101: 2020-11-23 00:02:12 ERROR: Backup of VM 101 failed - unable to parse volume ID '/tank/backup/timemachine/XXXXX' `

**Comment by ThomasLamprecht** [comment]
Hi,

GitHub is only used as mirror, please direct issues to one of the places linked in:
https://pve.proxmox.com/pve-docs/pve-admin-guide.html#getting_help

**Comment by TuncTaylan** [comment]
For the rest of the internet, the mentioned issue was already fixed in the next version.
