### ISSUE TITLE
Backups are sent to remote server in clear text when encryption key file is not found in place even though encryption is configured

### ISSUE THREAD

**Issue by DistortedBit** [proxmox/pve-storage#9]
Please see the full details here
https://gist.github.com/DistortedBit/6d3cd9c8d14a22376c6f43344306aaba

**Comment by Fabian-Gruenbichler** [comment]
thanks - see linked gist and forum post. this github org is just a mirror of our official git repos at git.proxmox.com, we don't use it in any active capacity (unfortunately, disabling issue creation is not possible).
